DELETE FROM equipe_instituicao;

DELETE FROM instituicao;

INSERT INTO instituicao (descricao, ativo) VALUES
                                               ('Abrigo de Animais A4', 1),
                                               ('Abrigo de Animais Arca do Tota', 1),
                                               ('APAE', 1),
                                               ('Casa da Criança Drº João Moura', 1),
                                               ('Casa da Lili', 1),
                                               ('Casa de Acolhida Nossa Senhora de Lourdes – (Essa está em construção) – Próximo à FAP.', 1),
                                               ('Casa de Acolhida Pe. Ibiapina', 1),
                                               ('Casa de Acolhida Rosa Mística', 1),
                                               ('Casa de Acolhida Santa Isabel de Hungria', 1),
                                               ('Casa de Acolhida São Paulo da Cruz', 1),
                                               ('Casa do Menino', 1),
                                               ('Cata Mais', 1),
                                               ('Centelhas de Cristo', 1),
                                               ('CENTRAC - Centro de Arte e Cultura', 1),
                                               ('Comissão Pastoral da Terra – CPT', 1),
                                               ('COTRAMARE', 1),
                                               ('Fazenda do Sol', 1),
                                               ('Fraternidade Irmãos de Francisco', 1),
                                               ('Hospital da FAP', 1),
                                               ('Homens de Cristo – Casa Evangélica em São Sebastião de Lagoa de Roça (Pastor Francisco)', 1),
                                               ('Instituto dos Cegos', 1),
                                               ('Lar da Sagrada Face', 1),
                                               ('Movimento dos Atingidos pela Barragem de Acauã (MAB Acauã)', 1),
                                               ('Pastoral Carcerária', 1),
                                               ('Pastoral da Criança', 1),
                                               ('Pastoral da Mulher', 1),
                                               ('Pastoral da Pessoa Idosa', 1),
                                               ('Pastoral da Saúde', 1),
                                               ('Pastoral da Sobriedade', 1),
                                               ('Pastoral de Acesso à Justiça e Direitos Humanos', 1),
                                               ('Pastoral de Pessoas em situação de Rua', 1),
                                               ('Pastoral das Necessidades Especiais (Surdos, cegos, cadeirantes, etc)', 1),
                                               ('Pastoral Operária', 1),
                                               ('Répteis da Caatinga', 1),
                                               ('Santuário da Divina Misericórdia', 1),
                                               ('São Vicente de Paulo', 1);
